### ISSUE TITLE
 [ERR_HTTP_HEADERS_SENT] and Jailbreak context failed

### ISSUE THREAD

**Issue by Rueby** [AmmoniaM/Spermack#10]
In tavern I'm getting the following error, I checked slack, it seems not to be going through fully? Any ideas how to fix this? It was working fine few hours ago.

```
node:internal/errors:484
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (D:\AI Stuff\TavernAI\SillyLossy-Cohee fork\SillyTavern-1.4.9\node_modules\express\lib\response.js:794:10)
    at ServerResponse.send (D:\AI\TavernAI\SillyLossy-Cohee fork\SillyTavern-1.4.9\node_modules\express\lib\response.js:174:12)
    at ServerResponse.json (D:\AI\TavernAI\SillyLossy-Cohee fork\SillyTavern-1.4.9\node_modules\express\lib\response.js:278:15)
    at ServerResponse.send (D:\AI\TavernAI\SillyLossy-Cohee fork\SillyTavern-1.4.9\node_modules\express\lib\response.js:162:21)
    at D:\AI\TavernAI\SillyLossy-Cohee fork\SillyTavern-1.4.9\server.js:2204:38
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v19.1.0
Press any key to continue . . .
```

And getting 

```
blocks length: 12039
Sent 0
Trace: Error: Jailbreak context failed, reply was:  "[ACK]"
    at WebSocket.<anonymous> (D:\AI\TavernAI\Spermack-main\slack.js:316:27)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (D:\AI\TavernAI\Spermack-main\node_modules\ws\lib\websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (D:\AI\TavernAI\Spermack-main\node_modules\ws\lib\receiver.js:541:14)
    at Receiver.getData (D:\AI\TavernAI\Spermack-main\node_modules\ws\lib\receiver.js:459:17)
    at Receiver.startLoop (D:\AI\TavernAI\Spermack-main\node_modules\ws\lib\receiver.js:158:22)
    at Receiver._write (D:\AI\TavernAI\Spermack-main\node_modules\ws\lib\receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at WebSocket.<anonymous> (D:\AI\TavernAI\Spermack-main\slack.js:352:19)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (D:\AI\TavernAI\Spermack-main\node_modules\ws\lib\websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (D:\AI\TavernAI\Spermack-main\node_modules\ws\lib\receiver.js:541:14)
    at Receiver.getData (D:\AI\TavernAI\Spermack-main\node_modules\ws\lib\receiver.js:459:17)
    at Receiver.startLoop (D:\AI\TavernAI\Spermack-main\node_modules\ws\lib\receiver.js:158:22)
    at Receiver._write (D:\AI\TavernAI\Spermack-main\node_modules\ws\lib\receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
Jailbreak context failed retries left: 3
+ Retrying: retryable error found while attempted to streamResponse: Jailbreak context failed
{ ok: false, error: 'internal_error' }
```

**Comment by Rueby** [comment]
Not sure why but it works now?
